# for local development only
version: '3.9'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
      POSTGRES_USER: "${DB_USER:-user}"
      POSTGRES_DB: db
    volumes:
      - type: volume
        source: app_data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  app_data:
